export type HazardType = 'FLOOD' | 'LANDSLIDE' | 'CLOUDBURST' | 'CYCLONE' | 'SEISMIC_ANOMALY' | 'DAM_BREACH' | 'URBAN_FLOOD' | 'WILDFIRE' | 'COASTAL_SURGE';
export type OperationalMode = 'PRE_DISASTER' | 'POST_DISASTER_EMERGENCY';
export type SeverityLevel = 'LEVEL_0_NORMAL' | 'LEVEL_1_MONITOR' | 'LEVEL_2_WATCH' | 'LEVEL_3_WARNING' | 'LEVEL_4_CRITICAL' | 'LEVEL_5_MASS_EMERGENCY';
export type UserRole = 'SUPER_ADMIN' | 'STATE_AUTHORITY' | 'DISTRICT_AUTHORITY' | 'FIELD_OFFICER' | 'POLICE' | 'FIRE_RESCUE' | 'MEDICAL_OFFICER' | 'SHELTER_MANAGER' | 'CITIZEN';
export type MapIntelligenceMode = 'LIVE_DISASTER' | 'PRE_DISASTER_RISK' | 'RED_ZONE' | 'POPULATION_EXPOSURE' | 'BUILDING_VULNERABILITY' | 'EVACUATION' | 'RESCUE' | 'OFFICER_DEPLOYMENT' | 'SHELTER_CAPACITY' | 'SATELLITE_INTELLIGENCE' | 'SENSOR_NETWORK' | 'WEATHER' | 'HISTORICAL_EVENTS' | 'RELOCATION_PLANNING';
export type BuildingStatus = 'SAFE' | 'MONITOR' | 'WATCH' | 'HIGH_RISK' | 'CRITICAL' | 'EVACUATE' | 'EVACUATED' | 'TRAPPED' | 'COLLAPSED' | 'SEARCH_REQUIRED' | 'RESCUE_COMPLETE' | 'UNKNOWN';
export type DamageClassification = 'NO_VISIBLE_DAMAGE' | 'MINOR' | 'MODERATE' | 'SEVERE' | 'COLLAPSED' | 'UNKNOWN';

export interface Building { id: string; code: string; name: string; address: string; lat: number; lng: number; floors: number; buildingType: 'RESIDENTIAL' | 'COMMERCIAL' | 'SCHOOL' | 'HOSPITAL' | 'INDUSTRIAL' | 'GOVERNMENT'; registeredPopulation: number; estimatedOccupancy: number; vulnerableGroups: { children: number; elderly: number; disabled: number; highRiskMed: number }; structuralType: 'REINFORCED_CONCRETE' | 'UNREINFORCED_MASONRY' | 'TIMBER_MUD' | 'STEEL_FRAME'; constructionYear: number; soilCategory: 'ALLUVIAL_LOOSE' | 'CLAY_EXPANSIVE' | 'ROCK_STABLE' | 'RIVER_BED_SAND'; elevationMeters: number; nearestRiverDistanceKm: number; currentHazardScore: number; structuralVulnerabilityScore: number; overallRiskScore: number; evacuationStatus: BuildingStatus; evacuationPriority: 'NONE' | 'LOW' | 'MEDIUM' | 'HIGH' | 'CRITICAL'; nearestShelterId: string; nearestSafeRoute: string; estimatedTrappedCount?: number; collapseConfidence?: number; damageLevel?: DamageClassification; sosCount?: number; lastSensorReading?: string; heightExtrusion?: number; }
export type SensorStatus = 'ONLINE' | 'DEGRADED' | 'OFFLINE' | 'ANOMALY' | 'CRITICAL' | 'MAINTENANCE';
export interface SensorNode { id: string; nodeCode: string; name: string; type: 'WATER_LEVEL' | 'RAINFALL' | 'SOIL_MOISTURE' | 'SEISMIC_VIBRATION' | 'WEATHER_BARO' | 'TILT'; lat: number; lng: number; gatewayId: string; batteryPercentage: number; signalStrengthDbm: number; status: SensorStatus; firmwareVersion: string; lastSyncTimestamp: string; currentReading: { value: number; unit: string; secondaryValue?: number; secondaryUnit?: string; anomalyDetected: boolean; anomalyConfidence?: number }; telemetryHistory: { timestamp: string; value: number }[]; }
export interface CommunityGateway { id: string; code: string; name: string; locationName: string; lat: number; lng: number; connectedSensorsCount: number; backhaulType: 'CELLULAR_4G_5G' | 'SATELLITE_DIRECT' | 'LORA_MESH' | 'HYBRID'; signalQuality: 'EXCELLENT' | 'GOOD' | 'FAIR' | 'POOR'; storageStatus: 'SYNCED' | 'BUFFERING' | 'OFFLINE_CACHE'; bufferedPackets: number; batteryPercentage: number; powerSource: 'SOLAR_BACKUP' | 'GRID' | 'BATTERY_ONLY'; lastSync: string; status: 'ONLINE' | 'DEGRADED' | 'OFFLINE'; }
export interface Shelter { id: string; code: string; name: string; lat: number; lng: number; capacity: number; currentOccupancy: number; amenities: { waterLiters: number; foodDaysRemaining: number; toiletsCount: number; medicalBedCount: number; backupPower: boolean; womenChildrenSpecialCare: boolean; wheelchairAccessible: boolean; satellitePhone: boolean; securityPersonnel: number }; contactOfficer: string; contactPhone: string; status: 'OPEN_ACCEPTING' | 'NEAR_CAPACITY' | 'FULL' | 'ISOLATED' | 'STANDBY'; assignedVehicles: number; }
export interface Hospital { id: string; name: string; lat: number; lng: number; totalBeds: number; occupiedBeds: number; icuBedsAvailable: number; emergencyRoomStatus: 'NORMAL' | 'ELEVATED' | 'CRITICAL_LOAD'; ambulancesStationed: number; bloodSupplyStatus: 'ADEQUATE' | 'LIMITED' | 'CRITICAL_SHORTAGE'; traumaCenterLevel: 1 | 2 | 3; powerStatus: 'GRID_STABLE' | 'GENERATOR_RUNNING'; contact: string; }
export interface RescueTeam { id: string; name: string; department: 'NDRF' | 'SDRF' | 'FIRE_RESCUE' | 'POLICE_QRT' | 'CIVIL_DEFENSE' | 'MEDICAL_RAPID'; personnelCount: number; leaderName: string; specialization: 'WATER_FLOOD' | 'STRUCTURAL_COLLAPSE' | 'MEDICAL_TRIAGE' | 'HILL_LANDSLIDE' | 'GENERAL_EVAC'; status: 'AVAILABLE' | 'ASSIGNED' | 'EN_ROUTE' | 'ON_SITE_RESCUE' | 'RETURNING' | 'OFF_DUTY'; currentMissionId?: string; lat: number; lng: number; equipment: string[]; assignedVehicle: string; contactRadio: string; }
export interface Ambulance { id: string; vehicleNumber: string; lat: number; lng: number; status: 'AVAILABLE' | 'EN_ROUTE' | 'AT_INCIDENT' | 'TRANSPORTING' | 'AT_HOSPITAL' | 'MAINTENANCE'; type: 'ADVANCED_LIFE_SUPPORT' | 'BASIC_LIFE_SUPPORT' | 'BOAT_AMBULANCE'; destinationHospital?: string; etaMinutes?: number; currentIncidentId?: string; paramedicCount: number; }
export interface RoadSegment { id: string; name: string; coordinates: [number, number][]; status: 'OPEN' | 'SLOW' | 'BLOCKED' | 'FLOODED' | 'DAMAGED' | 'EMERGENCY_ONLY'; blockageReason?: string; clearanceEtaMinutes?: number; waterDepthCm?: number; speedLimitKmh: number; }
export interface Incident { id: string; code: string; title: string; type: HazardType; severity: SeverityLevel; status: 'REPORTED' | 'VERIFIED' | 'RESPONDING' | 'UNDER_CONTROL' | 'RESOLVED'; lat: number; lng: number; affectedRadiusMeters: number; estimatedExposedPopulation: number; vulnerableCount: number; assignedTeams: string[]; assignedAmbulances: string[]; targetShelters: string[]; timestamp: string; commander: string; description: string; actionItems: string[]; sosRequestsCount: number; }
export interface SOSRequest { id: string; citizenName: string; phone: string; lat: number; lng: number; buildingId?: string; timestamp: string; trappedCount: number; medicalUrgency: 'CRITICAL_INJURY' | 'OXYGEN_NEEDED' | 'FLOOD_RISING' | 'CHILDREN_ELDERLY' | 'SAFE_BUT_CUTOFF'; batteryLevel: number; networkType: 'CELLULAR' | 'LORA' | 'SATELLITE_MSG'; status: 'PENDING_TRIAGE' | 'OFFICER_DISPATCHED' | 'RESCUE_IN_PROGRESS' | 'RESCUED'; assignedTeamId?: string; notes: string; }
export interface PublicAlert { id: string; title: string; hazardType: HazardType; urgency: 'HIGH' | 'CRITICAL' | 'PRECAUTIONARY' | 'ADVISORY'; targetDistrict: string; targetRadiusKm: number; centerLat: number; centerLng: number; languages: Record<string, { headline: string; body: string; safeAction: string }>; channels: ('SMS' | 'PUSH' | 'BROWSER' | 'VOICE_BROADCAST' | 'SACHET_CAP')[]; sentTimestamp: string; metrics: { targetedHouseholds: number; delivered: number; acknowledged: number; failed: number }; recommendedSafeShelter: string; }
export interface RelocationSite { id: string; name: string; category: 'IMMEDIATE' | 'SHORT_TERM' | 'MEDIUM_TERM_PERMANENT'; lat: number; lng: number; elevationMeters: number; landAreaHectares: number; totalPopulationCapacity: number; currentRelocated: number; hazardExposureScore: number; carryingCapacity: { waterCapacityPersons: number; foodLogisticsDays: number; sanitationIndexScore: number; medicalCenterProximityKm: number; roadConnectivityKmh: number; electricityGridStatus: 'STABLE' | 'TEMPORARY_GEN' | 'SOLAR_MICROGRID'; effectiveScore: number; warningLevel: 'GREEN' | 'YELLOW' | 'ORANGE' | 'RED' }; infrastructureReady: boolean; notes: string; }
export interface AuditLog { id: string; timestamp: string; officerName: string; role: string; action: string; previousState?: string; newState: string; reason: string; dataReference: string; }
export interface TimelineEvent { id: string; timestamp: string; source: string; title: string; description: string; severity: string; verified: boolean; dataPayload?: unknown; }
export interface SystemHealthMetrics { apiHealthPercent: number; dbLatencyMs: number; aiInferenceLatencyMs: number; gisTileLatencyMs: number; iotGatewayOnlinePercent: number; satelliteSyncState: 'CONNECTED' | 'DEGRADED' | 'SIMULATION' | 'OFFLINE'; lastSatelliteSyncTimestamp: string; overallDataQualityPercent: number; activeSensorsCount: number; totalSensorsCount: number; telemetryIngestedLastHour: number; }
